version: '2'
services:
  sentry-cron:
    environment:
      SENTRY_EMAIL_USE_TLS: ${sentry_server_email_tls}
      SENTRY_EMAIL_HOST: ${sentry_email_host}
      SENTRY_EMAIL_PASSWORD: ${sentry_email_password}
      SENTRY_EMAIL_PORT: '${sentry_email_port}'
      SENTRY_EMAIL_USER: ${sentry_email_user}
      SENTRY_SECRET_KEY: ${sentry_secret_key}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: "${postgres_port}"
      SENTRY_DB_NAME: ${sentry_db_name}
      SENTRY_DB_USER: ${sentry_db_user}
      SENTRY_DB_PASSWORD: ${sentry_db_pass}
      SENTRY_FILESTORE_DIR:
    labels:
      io.rancher.container.hostname_override: container_name
    tty: true
    command:
    - run
    - cron
    image: sentry:8.20.0
    links:
    - sentry-redis:redis
    external_links:
    - ${postgres_link}:postgres
    stdin_open: true
    volumes:
      - SENTRY:/var/lib/sentry/files
  sentry-redis:
    labels:
      io.rancher.container.hostname_override: container_name
    tty: true
    image: redis:3.2-alpine
    stdin_open: true
  sentry:
    environment:
      SENTRY_EMAIL_USE_TLS: ${sentry_server_email_tls}
      SENTRY_EMAIL_HOST: ${sentry_email_host}
      SENTRY_EMAIL_PASSWORD: ${sentry_email_password}
      SENTRY_EMAIL_PORT: '${sentry_email_port}'
      SENTRY_EMAIL_USER: ${sentry_email_user}
      SENTRY_SECRET_KEY: ${sentry_secret_key}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: "${postgres_port}"
      SENTRY_DB_NAME: ${sentry_db_name}
      SENTRY_DB_USER: ${sentry_db_user}
      SENTRY_DB_PASSWORD: ${sentry_db_pass}
    labels:
      io.rancher.container.hostname_override: container_name
    tty: true
    command:
    - /bin/bash
    - -c
    - sentry upgrade --noinput && sentry createuser --email ${sentry_initial_user_email} --password ${sentry_initial_user_password} --superuser && /entrypoint.sh run web || /entrypoint.sh run web
    image: sentry:8.20.0
    links:
    - sentry-redis:redis
    external_links:
    - ${postgres_link}:postgres
    stdin_open: true
    volumes:
      - SENTRY:/var/lib/sentry/files
  sentry-worker:
    environment:
      SENTRY_EMAIL_USE_TLS: ${sentry_server_email_tls}
      SENTRY_EMAIL_HOST: ${sentry_email_host}
      SENTRY_EMAIL_PASSWORD: ${sentry_email_password}
      SENTRY_EMAIL_PORT: '${sentry_email_port}'
      SENTRY_EMAIL_USER: ${sentry_email_user}
      SENTRY_SECRET_KEY: ${sentry_secret_key}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: "${postgres_port}"
      SENTRY_DB_NAME: ${sentry_db_name}
      SENTRY_DB_USER: ${sentry_db_user}
      SENTRY_DB_PASSWORD: ${sentry_db_pass}
    labels:
      io.rancher.container.hostname_override: container_name
    tty: true
    command:
    - run
    - worker
    image: sentry:8.20.0
    links:
    - sentry-redis:redis
    external_links:
    - ${postgres_link}:postgres
    stdin_open: true
    volumes:
      - SENTRY:/var/lib/sentry/files

volumes:
  SENTRY:
    driver: rancher-nfs
